# Generated by Django 5.0.7 on 2024-07-10 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SkosLabel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="The entities label or name.",
                        max_length=100,
                    ),
                ),
                (
                    "label_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("prefLabel", "prefLabel"),
                            ("altLabel", "altLabel"),
                            ("hiddenLabel", "hiddenLabel"),
                        ],
                        help_text="The type of the label.",
                        max_length=30,
                    ),
                ),
                (
                    "isoCode",
                    models.CharField(
                        blank=True,
                        help_text="The ISO 639-3 code for the label's language.",
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkosNamespace",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "namespace",
                    models.URLField(
                        blank=True, default="http://www.vocabs/provide-some-namespace/"
                    ),
                ),
                (
                    "prefix",
                    models.CharField(blank=True, default="histogis", max_length=50),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkosConceptScheme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dc_title", models.CharField(blank=True, max_length=300)),
                ("dct_creator", models.URLField(blank=True)),
                ("legacy_id", models.CharField(blank=True, max_length=200)),
                (
                    "namespace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vocabs.skosnamespace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkosConcept",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pref_label", models.CharField(blank=True, max_length=300)),
                (
                    "pref_label_lang",
                    models.CharField(blank=True, default="eng", max_length=3),
                ),
                ("definition", models.TextField(blank=True)),
                (
                    "definition_lang",
                    models.CharField(blank=True, default="eng", max_length=3),
                ),
                ("notation", models.CharField(blank=True, max_length=300)),
                ("legacy_id", models.CharField(blank=True, max_length=200)),
                (
                    "name_reverse",
                    models.CharField(
                        blank=True,
                        help_text='Inverse relation like:         "is sub-class of" vs. "is super-class of".',
                        max_length=255,
                        verbose_name="Name reverse",
                    ),
                ),
                (
                    "broader_concept",
                    models.ForeignKey(
                        blank=True,
                        help_text="Broader Term.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="narrower_concepts",
                        to="vocabs.skosconcept",
                        verbose_name="Broader Term",
                    ),
                ),
                (
                    "skos_broader",
                    models.ManyToManyField(
                        blank=True, related_name="narrower", to="vocabs.skosconcept"
                    ),
                ),
                (
                    "skos_broadmatch",
                    models.ManyToManyField(
                        blank=True, related_name="broadmatch", to="vocabs.skosconcept"
                    ),
                ),
                (
                    "skos_closematch",
                    models.ManyToManyField(
                        blank=True, related_name="closematch", to="vocabs.skosconcept"
                    ),
                ),
                (
                    "skos_exactmatch",
                    models.ManyToManyField(
                        blank=True, related_name="exactmatch", to="vocabs.skosconcept"
                    ),
                ),
                (
                    "skos_narrower",
                    models.ManyToManyField(
                        blank=True, related_name="broader", to="vocabs.skosconcept"
                    ),
                ),
                (
                    "skos_related",
                    models.ManyToManyField(
                        blank=True, related_name="related", to="vocabs.skosconcept"
                    ),
                ),
                (
                    "scheme",
                    models.ManyToManyField(
                        blank=True,
                        related_name="has_concepts",
                        to="vocabs.skosconceptscheme",
                    ),
                ),
                (
                    "namespace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vocabs.skosnamespace",
                    ),
                ),
            ],
        ),
    ]
