# Generated by Django 5.0.7 on 2024-07-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vocabs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skosconcept",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="skosconceptscheme",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="skoslabel",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="skosnamespace",
            options={"ordering": ["id"]},
        ),
    ]
