# Generated by Django 2.0.5 on 2018-06-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(help_text='Earliest date this entity captures', verbose_name='Start Date.')),
                ('end_date', models.DateField(help_text='Latest date this entity captures', verbose_name='End Date.')),
                ('date_accuracy', models.CharField(choices=[('Y', 'Year'), ('YM', 'Month'), ('DMY', 'Day')], default='Y', max_length=3)),
            ],
        ),
    ]
