# Generated by Django 5.0.7 on 2024-07-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("idprovider", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="idprovider",
            options={"ordering": ["id"]},
        ),
    ]
