# Generated by Django 2.0.6 on 2018-08-27 10:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idprovider', '0001_initial'),
        ('vocabs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the source', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Some verbose description of the source', null=True, verbose_name='Description')),
                ('quote', models.TextField(blank=True, help_text='How to quote.', null=True, verbose_name='Quote')),
                ('original_url', models.URLField(blank=True, help_text='URL from where the data was downloaded', null=True, verbose_name='URL')),
                ('downloaded', models.DateTimeField(blank=True, help_text='When was the data downloaded', null=True, verbose_name='Date of data download')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TempSpatial',
            fields=[
                ('idprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='idprovider.IdProvider')),
                ('name', models.CharField(max_length=250, verbose_name='The objects name')),
                ('alt_name', models.CharField(help_text="Alternative Names, use '; ' as separator in case of more names.", max_length=500, verbose_name='Alternative Names')),
                ('start_date', models.DateField(help_text='Earliest date this entity captures', verbose_name='Start Date.')),
                ('end_date', models.DateField(help_text='Latest date this entity captures', verbose_name='End Date.')),
                ('date_accuracy', models.CharField(choices=[('Y', 'Year'), ('YM', 'Month'), ('DMY', 'Day')], default='Y', max_length=3)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('orig_id', models.CharField(blank=True, max_length=255, null=True)),
                ('quality', models.CharField(choices=[('red', 'red'), ('yellow', 'yellow'), ('green', 'green')], default='yellow', max_length=2, null=True)),
                ('administrative_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_unit', to='vocabs.SkosConcept')),
                ('part_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_children', to='shps.TempSpatial')),
                ('source', models.ForeignKey(blank=True, help_text='The source of this data.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_of', to='shps.Source', verbose_name='Source')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('idprovider.idprovider',),
        ),
        migrations.CreateModel(
            name='TempStatialRel',
            fields=[
                ('idprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='idprovider.IdProvider')),
                ('start_date', models.DateField(help_text='Earliest date this relation captures', verbose_name='Start Date.')),
                ('end_date', models.DateField(help_text='Latest date this relation captures', verbose_name='End Date.')),
                ('date_accuracy', models.CharField(choices=[('Y', 'Year'), ('YM', 'Month'), ('DMY', 'Day')], default='Y', max_length=3)),
                ('instance_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_instance_a', to='shps.TempSpatial')),
                ('instance_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_instance_b', to='shps.TempSpatial')),
                ('relation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tmp_spatial_rel_relation', to='vocabs.SkosConcept')),
            ],
            bases=('idprovider.idprovider',),
        ),
    ]
